### PR TITLE
change the way contact is spelled

### PR DESCRIPTION
**Pull request by khamper**
depending on how many of your contacts are online

### CODE REVIEW

**Comment by vlOd2** [comment]
Code style conflicts too much (lack of spaces)

**Comment by khamper** [comment]
Should I add the spaces and create another pull request or were you not willing to keep this?

**Comment by vlOd2** [comment]
`were you not willing to keep this`
Also that, Skype 0.97 had it like this, i.e it would show 0 Contacts Online etc

**Comment by vlOd2** [comment]
Great feature in itself, but ruins a bit of the authenticity

**Pull request closed without merging**
