### PR TITLE
Color text implementation

### PR DESCRIPTION
**Pull request by matthilde**
Here's an attempt at making some kind of coloured text format without using Rich Text Format (and therefore make it easier to parse).

This format uses a #XXXXXX-style hex to specify a color.

```
#FF0000Red Text #0000FF Blue Text. This (##) is an escaped hashtag
```

### CODE REVIEW

**Comment by vlOd2** [comment]
Great idea, will need to replace the escape character to something less commonly used or make it be escapped automatically when sending

**Comment by matthilde** [comment]
I did it real quick. I think we should use something like the backslash maybe?
Something like \\\<colorcode>. We could use this for more things as well.

**Comment by iamatsomeone** [comment]
i think you should use `<colorcode > instead

**Comment by vlOd2** [comment]
It is ### now, so ###RRGGBB

**Comment by iamatsomeone** [comment]
ok

**Pull request merged**
