### PR TITLE
Change the Pinto! logo to have a subtle gradient.

### PR DESCRIPTION
**Pull request by iamatsomeone**
:root:root:root:root:root:root:root:root {

content: 'Lol';

}

### CODE REVIEW

**Comment by DexrnZacAttack** [comment]
I personally feel that it would be a little weird because of taskbar icons and things, plus all other logos would need to be updated, and the original blue skype logo I don't think had that.

**Comment by iamatsomeone** [comment]
> I personally feel that it would be a little weird because of taskbar icons and things, plus all other logos would need to be updated, and the original blue skype logo I don't think had that.

skype did have gradients on its logos, they just stopped using it with skype 8

**Comment by DexrnZacAttack** [comment]
Ah ok

**Comment by DexrnZacAttack** [comment]
Also it looks more like a drop shadow to me but maybe that's just me

**Comment by iamatsomeone** [comment]
> Also it looks more like a drop shadow to me but maybe that's just me

the andriod icon had that

**Comment by iamatsomeone** [comment]
and i think windows maybe

**Comment by vlOd2** [comment]
Your fork contains too many unrelated commits, please recreate it with only the relevant commit

**Pull request closed without merging**
